export const TOGGLE_EXAMPLE = 'TOGGLE_EXAMPLE';

export const GET_EXAMPLE = 'GET_EXAMPLE';
export const GET_EXAMPLE_SUCCESS = 'GET_EXAMPLE_SUCCESS';
export const GET_EXAMPLE_FAIL = 'GET_EXAMPLE_FAIL';
