export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const GET_COUNTRIES_FAIL = 'GET_COUNTRIES_FAIL';

export const GET_COUNTRY_DETAILS = 'GET_COUNTRY_DETAILS';
export const GET_COUNTRY_DETAILS_SUCCESS = 'GET_COUNTRY_DETAILS_SUCCESS';
export const GET_COUNTRY_DETAILS_FAIL = 'GET_COUNTRY_DETAILS_FAIL';

export const GET_PLAYERS_PER_COUNTRY = 'GET_PLAYERS_PER_COUNTRY';
export const GET_PLAYERS_PER_COUNTRY_SUCCESS =
  'GET_PLAYERS_PER_COUNTRY_SUCCESS';
export const GET_PLAYERS_PER_COUNTRY_FAIL = 'GET_PLAYERS_PER_COUNTRY_FAIL';

export const SEARCH_FOR_COUNTRY = 'SEARCH_FOR_COUNTRY';
export const UPDATE_COUNTRIES = 'UPDATE_COUNTRIES';
